services:

  service2:
    build:
      context: ./service2
    container_name: service2
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: "6831"
    expose:
      - "5000"
    ports:
      - "5001:5000"

  service1:
    build:
      context: ./service1
    container_name: service1
    environment:
      SERVICE2_URL: http://service2:5000/
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: "6831"
    depends_on:
      - service2
    ports:
      - "5000:5000"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector HTTP
      - "14250:14250" # Collector gRPC
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "6831:6831/udp" # Agent UDP
      - "6832:6832/udp" # Agent UDP
